# Generated by Django 4.2 on 2023-05-01 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_bith',
            new_name='date_of_birth',
        ),
    ]
