# Generated by Django 4.2 on 2023-05-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstance",
            name="due_back",
            field=models.DateField(
                blank=True,
                help_text="Введите конец срока статуса",
                null=True,
                verbose_name="Дата окончания статуса",
            ),
        ),
    ]
